syntax = "proto3";

package common.v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";


option go_package = "le github.com/ose-micro/grpc/gen/go/common/v1;commonv1";

enum FilterOp {
  OP_UNSPECIFIED = 0;
  EQ = 1;
  NE = 2;
  GT = 3;
  GTE = 4;
  LT = 5;
  LTE = 6;
  IN = 7;
  NIN = 8;
  REGEX = 9;
}

enum AggregationType {
  AGG_UNSPECIFIED = 0;
  SUM = 1;
  AVG = 2;
  COUNT = 3;
  MIN = 4;
  MAX = 5;
}

enum SortOrder {
  SORT_UNSPECIFIED = 0;
  ASC = 1;
  DESC = 2;
}

enum ComputedOperator {
  OCP_UNSPECIFIED = 0;
  MULTIPLY = 1;
  ADD = 2;
  DIVIDE = 3;
  SUBTRACT = 4;
  WEEK = 5;
  YEAR = 6;
  MONTH = 7;
  DAY_OF_MONTH = 8;
  TO_UPPER = 9;
  TO_LOWER = 10;
  CONCAT = 11;
  SUBSTR = 12;
  DATE_TRUNC = 13;
  IF_NULL = 14;
}

message Filter {
  string field = 1;
  FilterOp op = 2;
  string value = 3;
}

message Aggregation {
  AggregationType type = 1;
  string field = 2;
  string as = 3;
}

message SortOption {
  string field = 1;
  SortOrder order = 2;
}

message ComputedField {
  string name = 1;
  ComputedOperator operator = 2;
  repeated string operands = 3;
}

message FacetQuery {
  string name = 1;
  repeated Filter filters = 2;
  repeated string group_by = 3;
  repeated Aggregation aggregations = 4;
  repeated SortOption sort = 5;
  repeated ComputedField computed_fields = 6;
  int64 skip = 7;
  int64 limit = 8;
}

message Request {
  repeated FacetQuery facets = 1;
}

message Result {
  map<string, google.protobuf.Value> data = 1;
}

message Summary {
  map<string, google.protobuf.Value> records = 1;
}

message Summaries {
  repeated Summary records = 1;
}